OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_7EqGQg2RKl5FeRaNsYxzC2wI"
OPENAI_ORG_ID = "org-hHpg3w7aQRuAfRR682o0kyWw"
