
OPENAI_API_KEY = "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"

OPENAI_PROJECT_ID = "proj_7EqGQg2RKl5FeRaNsYxzC2wI"
OPENAI_ORG_ID = "org-hHpg3w7aQRuAfRR682o0kyWw"
