OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_7EqGQg2RKl5FeRaNsYxzC2w"
OPENAI_ORG_ID = "org-hHpg3w7aQRuAfRR682o0kyWw"
